server:
    port: 8301
spring:
    datasource:
        username: hyj
        password: mimamima1
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.31.79.44:3306/study
    jpa:
        open-in-view: false
    application:
        name: borrowservice
eureka:
    client:
        # 跟上面一样，需要指向Eureka服务端地址，这样才能进行注册
        service-url:
            defaultZone: http://localhost:8801/eureka, http://localhost:8802/eureka
feign:
    circuitbreaker:
        enabled: true