server:
    port: 8801
spring:
    application:
        name: eurekaserver
    datasource:
        username: hyj
        password: mimamima1
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/study
eureka:
    # 注意：这里由于我们修改成自定义的地址，需要在hosts文件中将其解析到127.0.0.1才能回到localhost
    # Mac下文件路径为/etc/hosts，Windows下为C:\Windows\system32\drivers\etc\hosts：
    instance:
        hostname: eureka01
    # 开启之前需要修改一下客户端设置（虽然是服务端
    client:
        # 由于我们是作为服务端角色，所以不需要获取服务端，改为false，默认为true
        fetch-registry: false
#        # 暂时不需要将自己也注册到Eureka
#        去掉register-with-eureka选项，让Eureka服务器自己注册到其他Eureka服务器，这样才能相互启用
#        注意：要显式地注明register-with-eureka: true，才能相互启用
        register-with-eureka: true
        # 将eureka服务端指向自己
        service-url:
            defaultZone: http://eureka02:8802/eureka
    server:
        enable-self-preservation: true