server:
    port: 8888
spring:
    datasource:
        username: hyj
        password: mimamima1
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/study
eureka:
    # 开启之前需要修改一下客户端设置（虽然是服务端
    client:
        # 由于我们是作为服务端角色，所以不需要获取服务端，改为false，默认为true
        fetch-registry: false
        # 暂时不需要将自己也注册到Eureka
        register-with-eureka: false
        # 将eureka服务端指向自己
        service-url:
            defaultZone: http://localhost:8888/eureka
    server:
        enable-self-preservation: false